version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.0.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Generate Coverage Report
          command: npm run coverage
      - store_test_results:
          path: ./test-results/

  docker-build-push:
    docker:
      - image: cimg/node:16.0.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t $DOCKER_USERNAME/system-monitor-api:latest .
      - run:
          name: Login to DockerHub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Push Docker Image
          command: docker push $DOCKER_USERNAME/system-monitor-api:latest

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
      - docker-build-push:
          requires:
            - build-and-test
